<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<?php echo $this->getChildHtml('header') ?>
<div id="main">
	<div class="container">
		<div class="col2 clearfix">
		<?php echo $this->getChildHtml('home_banner') ?>

		<?php echo $this->getChildHtml('after_body_start') ?>
		<div class="col-main bfL">
       		<?php echo $this->getChildHtml('breadcrumbs') ?>
			<?php echo $this->getChildHtml('global_messages') ?>
			<?php echo $this->getChildHtml('content') ?>
			<?php echo $this->getChildHtml('home_index') ?>
			<?php// echo $this->getChildHtml('home_recommend_list') ?>
		</div>
		<div class="col-left sidebar bfR">
			<?php echo $this->getChildHtml('home_right_ad') ?>
		</div>
		<?php echo $this->getChildHtml('home_recommend_list') ?>
		<?php echo $this->getChildHtml('home_new_list') ?>
		<?php echo $this->getChildHtml('home_hot_list') ?>
	</div>
    <div class="topbnt clearfix"><span><a href="#">顶部</a></span></div>
    </div>
</div>
<?php echo $this->getChildHtml('footer') ?>
<?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
