<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <h2 class="h2bg2"><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <div id="crosssell-products-list" class="products-grid">
    <?php foreach ($this->getItems() as $_item): ?>
        <dl class="item">
            <dt><a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(100); ?>"alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a></dt>
                <dd class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></dd>
                <dd><?php echo $this->getPriceHtml($_item, true) ?></dd>
                <dd><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></dd>
                
           
        </dl>
    <?php endforeach; ?>
    </div>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>