<?php
$group = Mage::getModel('customer/group');
$group->load(Mage::getModel('customer/session')->getCustomerGroupId());
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
	<div class="fieldset"> <?php echo $this->getBlockHtml('formkey')?>
		<h2 class="legend"><?php echo $this->__('Account Information') ?></h2>
		<ul class="form_list">
			<li class="fields"><span class="label-like">会员等级</span><strong><?php echo $group->getCode(); ?></strong></li>
			<li class="fields"><span class="label-like"><?php echo $this->__('User Name') ?><span class="required">*</span></span>
				<div class="input-box">
					<input type="text" name="username" id="username" value="<?php echo $this->htmlEscape($this->getCustomer()->getUsername()) ?>" class="input-text" disabled="disabled"/>
				</div>
			</li>
			<li class="fields"> <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?> </li>
			<li class="fields"><span class="label-like"><?php echo $this->__('Email Address') ?><span class="required">*</span></span>
				<div class="input-box">
					<input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" class="input-text" validata="required:true,email:true"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter email');?>"></span> </div>
			</li>
			<li class="fields"><span class="label-like"><?php echo $this->__('Phone') ?><span class="required">*</span></span>
				<div class="input-box">
					<input type="text" name="phone" id="phone" value="<?php echo $this->htmlEscape($this->getCustomer()->getPhone()) ?>" class="input-text" validata="required:true"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter phone.');?>"></span> </div>
			</li>
			<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
			<?php if ($_dob->isEnabled()): ?>
			<li class="fields"><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
			<?php endif ?>
			<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
			<?php if ($_gender->isEnabled()): ?>
			<li class="fields"><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
			<?php endif ?>
			<li class="fields">
				<div class="input-box">
					<input type="checkbox" class="checkbox" title="Change Password" onclick="changePassword(this.checked)" value="1" id="change_password" name="change_password">
					<span>
					<label for="change_password"><?php echo $this->__('Change Password');?></label>
					<span> </div>
			</li>
		</ul>
		<ul class="form_list changePassword" style="display: none;">
			<li class="fields"> <span class="label-like"><?php echo $this->__('Current Password') ?>:</span>
				<div class="input-box">
					<input type="password" class="input-text current_password" name="current_password" id="current_password"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter password');?>"></span> </div>
			</li>
			<li class="fields"> <span class="label-like"><?php echo $this->__('New Password') ?>:</span>
				<div class="input-box">
					<input type="password" class="input-text password" name="password" id="password"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter new password');?>"></span> </div>
			</li>
			<li class="fields"><span class="label-like"><?php echo $this->__('Confirm New Password') ?>:</span>
				<div class="input-box">
					<input type="password" class="input-text conpassword" name="confirmation" id="confirmation"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter confirm password');?>"></span> </div>
			</li>
		</ul>
		<div style="padding-left: 9.5em;">
			<button type="submit" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
		</div>
	</div>
</form>
<script type="text/javascript">
//<![CDATA[
var checkPassword = function(){
	if($('#password').val()!=$('#confirmation').val()){
		return {fail:true, msg:"<?php echo $this->__('Two input password does not agree.');?>"};
	}
	return true;
};
$(function() {
	makingware.form.getInstance('#form-validate', {
    	 error: {
             required: '<?php echo Mage::helper('core')->__('Required Fields');?>',
             minLength: '<?php echo Mage::helper('core')->__('At least %s characters');?>',
             email: '<?php echo Mage::helper('core')->__('Invalid %s address');?>'
         }
	 }).submit(function(){
		 return $(this).data('this').isValidata();
	 });
});

function changePassword(checked)
{
	if(checked) {
		$('.form_list.changePassword').show();
		$('#current_password').attr('validate','required:true');
		$('#password').attr('validate','required:true');
		$('#confirmation').attr('validate','required:true,method:checkPassword');
	} else {
		$('.form_list.changePassword').hide();
		makingware.form.getInstance('#form-validate').unvalidata('.changePassword');
	}
}
//]]>
</script>