<div class="account-login ">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
        <div class="col2-set clearfix">
            <h2 class="font16"><img src="<?php echo $this->getSkinUrl('') ?>images/title-process-login.gif" alt="登录注册"></h2>

            <div class="col-1 registered-users">
                <div class="content">
                    <h2><img src="<?php echo $this->getSkinUrl('') ?>images/title-login.gif" alt="亲爱的九蔬行会员，请登录"></h2>
                    <ul class="form_list">
                        <li class="fields">
                            <label for="email" class="label-like"><?php echo $this->__('Account') ?>: </label>

                            <div class="input-box">
                                <input type="text" name="login[username]" id="email" class="input-text"
                                       title="<?php echo $this->__('Email Address') ?>" validata="required:true"
                                       value="用户名/邮箱" style="color: rgb(153, 153, 153);"
                                       onfocus="if(this.value=='用户名/邮箱'){this.value=''; this.style.color='#333'}"
                                       onblur="if(this.value=='') {this.value='用户名/邮箱';this.style.color='#999';}"/>
                                <span class="prompt-msg" message=""></span>
                            </div>
                        </li>
                        <li class="fields">
                            <label for="pass" class="label-like"><?php echo $this->__('Password') ?>: </label>

                            <div class="input-box">
                                <input type="password" name="login[password]" class="input-text" id="pass"
                                       title="<?php echo $this->__('Password') ?>" validata="required:true"/>
                                <span class="prompt-msg" message=""></span>
                            </div>
                        </li>
                        <li class="fields"><input type="submit" class="login_bnt"
                                                  title="<?php echo $this->__('Login') ?>" name="send" id="send2" value="登录"/> <a
                                href="<?php echo $this->getForgotPasswordUrl() ?>">&nbsp;&nbsp;<?php echo $this->__('Forgot Your Password?') ?></a>
                        </li>
                    </ul>

                </div>
            </div>
            <div class="col-2 new-users">
                <div class="content">
                    <h2><img src="<?php echo $this->getSkinUrl('') ?>images/title-reg.png" alt="还不是雨生谷会员?即可注册"></h2>

                    <p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
                    <input type="button" title="<?php echo $this->__('Create an Account') ?>" class="reg_bnt" id="gotoreg" value="注册账户"
                           onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"/>

                    <div class="box-corner"></div>
                    <div class="box-bottom"></div>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    //<![CDATA[
    $(function() {
        makingware.form.getInstance('#login-form', {
            error: {
                required: '<?php echo Mage::helper('core')->__('Required Fields');?>',
                minLength: '<?php echo Mage::helper('core')->__('At least %s characters');?>',
                email: '<?php echo Mage::helper('core')->__('Invalid %s address');?>'
            }
        }).submit(function() {
                    return $(this).data('this').isValidata();
                });
    });
    //]]>
</script>
