<?php $_item = $this->getItem()?>

<tr>
	<td><dl class="product_row">
		<dt class="pic">
			<?php if ($this->hasProductUrl()):?>		
			<a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>">
			<?php endif;?>
			<img src="<?php echo $this->getProductThumbnail()->resize(55); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" />
			<?php if ($this->hasProductUrl()):?>
			</a>
			<?php endif;?>
		</dt>
		
		<dt class="product-name">
			<?php if ($this->hasProductUrl()):?>
			<a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
			<?php else: ?>
			<?php echo $this->htmlEscape($this->getProductName()) ?>
			<?php endif; ?>
			<input type="hidden" value="0" name="cart[<?php echo $_item->getId() ?>][wishlist]" />
		</dt>

		<?php if ($_options = $this->getOptionList()):?>
		<dd>
            <dl class="item-options">
			<?php foreach ($_options as $_option) : ?>
			<?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
			<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
			<dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
				<?php if (isset($_formatedOptionValue['full_view'])): ?>
				<div class="truncated_full_value">
					<dl class="item-options">
						<dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
						<dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
					</dl>
				</div>
				<?php endif; ?>
			</dd>
			<?php endforeach; ?>
		</dl></dd>
		<?php endif;?>
		<?php if ($messages = $this->getMessages()): ?>
		<?php foreach ($messages as $message): ?>
		<dd class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'] ?></dd>
		<?php endforeach; ?>
		</dl>
		<?php endif; ?>
		</td>
	<td>
		<span class="cart-price2">
		<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
		</span>
	</td>

	<td class="s-amount">
		<a class="minus" href="javascript:void(0);">-</a>
		<input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" />
		<a class="plus" href="javascript:void(0);">+</a>
	</td>
	<td>
		<span class="cart-price1">
		<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
		</span>
	</td>
	<?php echo $this->getLayout()->getBlock('checkout.cart.item.content')
					->setBlock($this)
					->setItem($_item)
					->toHtml();
	?>
	<td>
		<a href="<?php echo $this->getDeleteUrl() ?>" title="<?php echo $this->__('Remove item')?>" class="btn-remove2">
			<?php echo $this->__('Remove Product')?>
		</a>
	</td>
</tr>
