<script type="text/javascript">
//<![CDATA[
    var countryRegions = <?php echo $this->helper('directory')->getRegionJson();?>;
	var regionCitys = <?php echo $this->helper('directory')->getCityJson();?>;
	var cityAreas = <?php echo $this->helper('directory')->getAreaJson();?>;

	window.setAddressName = function(){
		$("#region").val($("#region_id").find('option[value="'+$("#region_id").val()+'"]').text());
		$("#city").val($("#city_id").find('option[value="'+$("#city_id").val()+'"]').text());
		$("#area").val($("#area_id").find('option[value="'+$("#area_id").val()+'"]').text());
	};

	window.regionChange = function(countryId){
		if(!countryId){countryId = $("#country_id").val();}
		if(countryRegions[countryId]){
			html = '';
			$.each(countryRegions[countryId], function(key, item) {
				html += '<option value="'+key+'">'+item.name+'</option>';
			});
			$("#region_id").html(html).trigger('change').show();
		}else{
			$("#region_id").empty();
			$("#city_id").empty().hide();
			$("#area_id").empty().hide();
		}
		setAddressName();
	};

	window.cityChange = function(regionId){
		if(!regionId){regionId = $("#region_id").val();}
		if(regionCitys[regionId]){
			html = '';
			$.each(regionCitys[regionId], function(key, item) {
				html += '<option value="'+key+'">'+item.name+'</option>';
			});
			$("#city_id").html(html).trigger('change').show();
		}else {
			$("#city_id").empty().hide();
			$("#area_id").empty().hide();
			$("#city").attr('type', 'text');
		}
		setAddressName();
	};

	window.areaChange = function(cityId){
		if(!cityId){cityId = $("#city_id").val();}
		if(cityAreas[cityId]){
			html = '';
			$.each(cityAreas[cityId], function(key, item) {
				html += '<option value="'+key+'">'+item.name+'</option>';
			});
			$("#area_id").html(html).show();
		}
		setAddressName();
	};
//]]>
</script>

<div class="shipping onepage_items clearfix">
	<h4><?php echo $this->__('Consignee information');?> <span><a id="address-edit" href="javascript:void(0)"><?php echo $this->__('Change');?></a></span> </h4>
	<div class="clearbolck"></div>
	<form id="address-form" style="display:none">
		<?php if ($this->customerHasAddresses()): ?>
		<div id="address-list" class="clearfix">
			<div class="stock_address"><strong><?php echo $this->__('Commonly used address');?></strong>
				<ul>
					<?php $index = 0; foreach ($this->getCustomer()->getAddresses() as $address):?>
					<?php if ($address->getCountryId() != $this->getCountryId() && !$this->getCountryMore()) {continue; } ?>
					<li <?php if($address->getId()==$this->getCustomer()->getDefaultShipping()):?>class="default"<?php endif;?>>
						<?php if ($this->getCountryMore()){echo $address->getCountryModel()->getName() . '-';} echo $address->getRegion(), $address->getCity(), $address->getArea(), $address->getStreetFull(); ?>
						<script type="text/javascript">
							var address<?php echo $index ++;?> = <?php echo json_encode(array(
								'customer_address_id'=> $address->getId(),
								'name' => $address->getName(),
								'country_id'=> $address->getCountryId(),
								'region_id' => $address->getRegionId(),
								'region' => $address->getRegion(),
								'city_id' => $address->getCityId(),
								'city' => $address->getCity(),
								'area_id' => $address->getAreaId(),
								'area' => $address->getArea(),
								'street' => $address->getStreet(),
								'postcode' => $address->getPostcode(),
								'telephone' => $address->getTelephone(),
								'fax' => $address->getFax(),
								'email' => $address->getEmail()
							), false); ?>;
						</script> 
					</li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
		<?php endif; ?>
		<ul class="form_list">
			<li> <span class="label"><?php echo $this->__('Shipped to Name');?>：</span>
				<div>
					<input name="name" type="text" class="input-text" value="<?php echo $this->getName();?>" validata="required:true,minLength:2"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter a name');?>"></span> </div>
			</li>
			<li style="display:none">
				<input type="hidden" name="customer_address_id" value="<?php echo $this->getCustomerAddressId();?>" />
			</li>
			<li style="display:none">
				<?php if ($this->getCountryMore()):?>
				<span class="label"><?php echo $this->__('Country');?>：</span>
				<div><?php echo $this->getCountryHtmlSelect();?></div>
				<?php else:?>
				<input id="country_id" name="country_id" type="hidden" value="<?php echo $this->getCountryId();?>" />
				<?php endif;?>
				<script type="text/javascript">
					$(function(){
						$("#country_id").change(function(){regionChange();}).trigger('change');
						<?php if ($countryId = $this->getCountryId()):?>
							$("#country_id").val("<?php echo $countryId;?>").trigger('change');
						<?php endif;?>
					});
				</script> 
			</li>
			<li> <span class="label"><?php echo $this->__('State/Province');?>：</span>
				<div id="address-item"> <span>
					<select id="region_id" name="region_id" validata="required:true">
					</select>
					<input id="region" name="region" type="hidden" value="<?php echo $this->getRegion();?>" />
					<span class="prompt-msg"></span> </span> <span>
					<select id="city_id" name="city_id">
					</select>
					<input id="city" name="city" type="hidden" value="<?php echo $this->getCity();?>" validata="required:true"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter city');?>"></span> </span> <span>
					<select id="area_id" name="area_id">
					</select>
					<input id="area" name="area" type="hidden" value="<?php echo $this->getArea();?>"/>
					</span> </div>
				<script type="text/javascript">
					$(function(){
						$("#region_id").change(function(){cityChange();}).trigger('change');
						$("#city_id").change(function(){areaChange();}).trigger('change');
						$("#area_id").change(function(){setAddressName();});

						<?php if ($regionId = $this->getRegionId()):?>
							$("#region_id").val('<?php echo $regionId;?>').trigger('change');
						<?php endif;?>
						<?php if ($cityId = $this->getCityId()):?>
							$("#city_id").val('<?php echo $cityId;?>').trigger('change');
						<?php endif;?>
						<?php if ($areaId = $this->getAreaId()):?>
							$("#area_id").val('<?php echo $areaId;?>').trigger('change');
						<?php endif;?>
					});
				</script> 
			</li>
			<li> <span class="label"><?php echo $this->__('Shipping Address');?>：</span>
				<div>
					<textarea cols="60" rows="3" id="street" name="street" class="input-text" validata="required:true"><?php echo $this->getStreet();?></textarea>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter your delivery address');?>"></span> </div>
			</li>
			<li> <span class="label"><?php echo $this->__('Zip/Postal Code');?>：</span>
				<div>
					<input name="postcode" type="text" class="input-text" value="<?php echo $this->getPostcode();?>" validata="number:true"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter your zip code receiving area');?>"></span> </div>
			</li>
			<?php if (!$this->isCustomerLoggedIn()): ?>
			<li> <span class="label"><?php echo $this->__('Email');?>：</span>
				<div>
					<input name="email" type="text" class="input-text" value="<?php echo $this->getEmail();?>" validata="required:true,email:true"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter your email');?>"></span> </div>
			</li>
			<?php endif; ?>
			<li> <span class="label"><?php echo $this->__('Telephone');?>：</span>
				<div>
					<input name="telephone" type="text" class="input-text" value="<?php echo $this->getTelephone();?>" validata="number:true"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter your contact Phone');?>"></span> </div>
			</li>
			<li> <span class="label"><?php echo $this->__('Fax');?>：</span>
				<div>
					<input name="fax" type="text" class="input-text" value="<?php echo $this->getFax();?>" validata="number:11"/>
					<span class="prompt-msg" message="<?php echo $this->__('Please enter your contact Fax');?>"></span> </div>
			</li>
			<?php if ($this->isCustomerLoggedIn()): ?>
			<li>
				<div>
					<input id="save_in_address_book" name="save_in_address_book" type="checkbox" value="1" />
					<?php echo $this->__('Save in address book');?>
					<input id="default_shipping" name="default_shipping" type="checkbox" value="1" />
					<?php echo $this->__('Set as default shipping address');?> </div>
				<script type="text/javascript">
					$(function(){
						$("#default_shipping").change(function(){
							if($(this).attr('checked')){
								$("#save_in_address_book").attr('checked', true);
							}
						}).trigger('change');
					});
				</script> 
			</li>
			<?php endif; ?>
			<div class="error" style="display:none;text-align:left;padding:2px 5px;border:2px solid red;margin-bottom:5px;"></div>
			<li>
				<input class="inputbutton" title="<?php echo $this->__('Determine the shipping address');?>" value="<?php echo $this->__('Determine the shipping address');?>" type="submit"/>
			</li>
		</ul>
	</form>
	<dl id="address-text">
	</dl>
</div>
<script type="text/javascript">
//<![CDATA[
     var $addressFrom = $('#address-form');
     var $addressText = $('#address-text');
     var $addressEdit = $('#address-edit');
     var $addressList = $('#address-list');
     
     makingware.form.getInstance($addressFrom, {
    	 error: {
             required: '<?php echo Mage::helper('core')->__('Required Fields');?>',
 			 minLength: '<?php echo Mage::helper('core')->__('At least %s characters');?>',
 			 maxLength: '<?php echo Mage::helper('core')->__('Up to %s characters');?>',
 			 number1: '<?php echo Mage::helper('core')->__('Must be a number');?>',
 			 number2: '<?php echo Mage::helper('core')->__('Must be %s digits');?>',
 			 regular: '<?php echo Mage::helper('core')->__('Invalid Input');?>',
 			 url: '<?php echo Mage::helper('core')->__('Invalid %s address');?>',
 			 email: '<?php echo Mage::helper('core')->__('Invalid %s address');?>',
 			 ip: '<?php echo Mage::helper('core')->__('Invalid %s address');?>'
         }
	 }).submit(function(){
		 var $this = $(this);
		 if($this.data('this').isValidata()){

			 var $errorTag = $this.find('.error').hide();
			 if(!($this.find('input:[name="telephone"]').val()) && !($this.find('input:[name="fax"]').val())) {
				 if($errorTag.size()) {
					 $this.find('input:[name="telephone"], input:[name="fax"]').addClass("error");
					 
					 }
	        	 return false;
		     }
			 
			 $.post("<?php echo $this->getUrl('*/*/saveAddress'); ?>", $this.serialize(), function(data) {
				 if(data){data = $.parseJSON(data);}else{data = {};}
         		 if(data.error){
         			if(data.error_messages){alert(data.error_messages);}
					else if(data.message){alert(data.message);}
					else{alert(data.error);}
         		 }else {
         			 $addressFrom.hide();
         			 $addressEdit.show();

 					 var html = '';
					 var prefix = '';
 					 $this.find("ul li").each(function(){
 	 					 var label, text;
 	 					 if(label = $(this).find('span[class="label"]').html()){
 	 	 					 text = [];
 							 $(this).find('*[name]').each(function(){
 								 if($(this).attr('tagName') == 'SELECT'){return true;}
 								 text.push($(this).val());
 							 });
							 if (label == '省份/地区：') {
								 prefix = text.join('');
								 return true;
							 }
							 text = text.join('');
							 if (text == '') {
								 text = '&nbsp;';
							 }
 							 html += '<dt>' + label + '</dt>';
 							 html += '<dd>' + prefix + text + '</dd>';
							 prefix = '';
 						 }
 					 });
 					 $addressText.html(html);

 					 // changed shipping/payment method
 					 if(data.section){
 	 					 $.each(data.section, function(key, value){
 	 	 					 if(value.name && value.html && $("#"+key).size()){$("#"+key).html(value.html);}
 						 });
 					 }
         		 }
	         });
		 }
		 return false;
	 });

     $(function(){
 		// address change
 		$addressEdit.click(function() {
 			$(this).hide();
 			$addressText.empty();
 			$addressFrom.show();
 			return false;
 		});
 		
 		$addressList.find('ul li').click(function(event) {
 	 		var $this = $(this);
 	 		$this.siblings().removeClass('click');
 	 		$this.addClass('click');

 	 		var $addressItem = eval('address' + $this.index());
 	 		if ($addressItem) {
 				$.each($addressItem, function(key, value) {
 					$addressFrom.find('[name="' + key + '"]').val($.trim(value)).attr('origvalue', $.trim(value)).trigger('change');
 				});
 	 		}
 		});

 		if ($addressList.find('ul li').length) {
 			$addressList.find('ul li.default').trigger('click');
 		}else {
 			$addressEdit.hide();
 			$addressFrom.show();
 		}

 		if ($addressFrom.find('input[name="name"]').val()) {$addressFrom.trigger('submit');}
 	});
//]]>
</script> 
