<?php $collection = $this->getStoreCategories();?>
<?php $i = 1; $j = 0; $k = 0; $jcount = 0; $kcout = 0; $menuname = "";?>  
    <?php foreach ($collection as $_category):?>
          <?php $menuname = "floatmenu0".$i;  $i = $i + 1;?>
<div class="menu" id = <?php echo $menuname?>  style="display: none" >
        <div class="dht">
          <div >
            <div class="navchild" style="background: url(&quot;http://i.vanclimg.com/header/20110117/navchild_03.gif&quot;) repeat-y scroll right top transparent;width: 620px; overflow: hidden;">
 		
		<div class="childleft">
	<?php //$jcount = count($_category->getChildren()); 
		$jcount = 0; $j = 0;?>
	<?php foreach($_category->getChildren() as $_childCategory): ?>
	<?php $jcount = $jcount + 1; ?>
	<?php endforeach?>
        <?php foreach($_category->getChildren() as $_childCategory):?>        
			<div class="childli">
                  	  <div class="childclass">
                    		<a href="<?php echo $this->getCategoryUrl($_childCategory)?>"><?php echo $_childCategory->getName()?></a>
                  	  </div>

                                <div class="childdetail">
		    <?php //$kcount = count($_childCategory->getChildren()); 
			$k = 0; $kcount = 0;?>
		    
                    <?php foreach($_childCategory->getChildren() as $_cchildCategory):?>
		    <?php $kcount = $kcount+1;?>
		    <?php endforeach ?>
                    <?php foreach($_childCategory->getChildren() as $_cchildCategory):?>
                    		<a name="head-subfloor-1_n" href="<?php echo $this->getCategoryUrl($_cchildCategory)?>" ><?php echo $_cchildCategory->getName()?></a>
                    <?php $k = $k + 1; if ($k != $kcount) : ?>   	
			<span>|</span>
                    <?php endif ?>
                    <?php endforeach?>

                  		</div>
			</div>
			<?php $j = $j +1; if($j != $jcount){ ?>
			<div class="LFkinddot">
                	</div>
			<?php }?>
        <?php endforeach?>
 
		</div>
              <div class="childright">
                <ul>
                  <li><a href="#" >新款男装</a></li>
                  <li><a href="#" name="head-subfloor-1_n" >热销推荐</a></li>
                  <li><a href="#" >男士衣柜</a></li>
                </ul>
              </div>

           </div>
          </div>
        </div>
      </div>

    <?php endforeach?>
<!--
<div id="sub_floor_menus" class="sub-floor-menus" style="display:none">
      <div class="menu" style="display: block; ">
        <div class="dht">
          <div >
            <div class="navchild" style="background: url(&quot;http://i.vanclimg.com/header/20110117/navchild_03.gif&quot;) repeat-y scroll right top transparent;width: 620px; overflow: hidden;">

              <div class="childleft">

                <div class="childli">
                  <div class="childclass">
                    <span>系列</span>
                  </div>
                  <div class="childdetail">
                    <a name="head-subfloor-1_n" href="#" >时尚T恤</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >基础POLO衫</a>
                    <span>|</span><a name="head-subfloor-1_n" href="#" class="track">NBA运动系列</a>
 <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >宅男系列</a>
<span>|</span>
                    <a name="head-subfloor-1_n" href="#" >迪士尼合辑</a>
                    <br>
                    <a name="head-subfloor-1_n" href="#" >风尚男装</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#">户外必备</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >运动系列</a>
                  </div>
                </div>
                <div class="LFkinddot">
                </div>

                <div class="childli">
                  <div class="childclass">
                    <span>上装</span>
                  </div>
                  <div class="childdetail">
                    <a name="head-subfloor-1_n" href="#" >衬衫</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >POLO衫</a>
 <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >T恤</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >大衣</a>
                    <span>|</span>
 <a name="head-subfloor-1_n" href="#" >西服</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >风衣</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#">冲锋衣</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >夹克</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >针织衫</a>
                    <br>
                    <a name="head-subfloor-1_n" href="#" >卫衣</a>
                    <span>|</span>
                    <a name="head-subfloor-1_n" href="#" >家居服</a>
                  </div>
                </div>

              </div>
              <div class="childright">
                <ul>
                  <li><a href="#" >新款男装</a></li>
                  <li><a href="#" name="head-subfloor-1_n" >热销推荐</a></li>
                  <li><a href="#" >男士衣柜</a></li>
                </ul>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
--!>
