<div class="cmspages">
<div class="page-title"><h1> 订单查询</h1></div>
<form action="<?php echo Mage::getUrl('searchorder/order/order') ?>" method="post" id="searchorder-form">
<p>
请输入你的订单号：&nbsp;&nbsp;&nbsp;&nbsp;
<input type="text" name="order_id" id="order_id" /><br /><br />
请输入订单的收件人：
<input type="text" name="shipping_name" id="shipping_name" /><br /><br />
<input type="submit" name="input" value="订单查询" class="inputbutton">
</p>
</form><br />
<br />
<br />

</div>
