<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
  <label for="newsletter"><em>想获取最新上架信息吗？</em></label>
  <div class="alertfrom">
    <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="ipt" />
    <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="bnt"><?php echo $this->__('Subscribe') ?></button>
  </div>
</form>
